language: generic
sudo: required

services: 
  - docker

before-install: 
  - docker build -t frontend/dockerized-react -f Dockerfile.dev .

 script: 
  - docker run -e CI=true frontend/dockerized-react/docker-react npm run test 